### ISSUE TITLE
PyLops v2 Notebook - no plots on colab

### ISSUE THREAD

**Issue by stevejpurves** [PyLops/pylops_transform2022#2]
After running the PyLops_v2 notebook on colab I cannot see any plots, the cells with plot commands just show empty outputs.

![image](https://user-images.githubusercontent.com/1473646/163991806-ecb0988f-5f44-4225-bf42-87e93e911279.png)

I'm running colab from the link in the readme in google chrome. The Decon.ipynb notebook works fine for me.

**Comment by mrava87** [comment]
Thanks for noticing this. @cako I was facing the same issue, switched to `%matplotlib inline` and seems fine. Was it working for you with `%matplotlib widget`?

**Comment by stevejpurves** [comment]
I'm also seeing errors for missing `ipympl` when running it on binder - switching to `inline` gets past that there too

**Comment by cako** [comment]
Hi @stevejpurves thanks for the heads up. For Colab, there is a cell saying:

```python
# Uncomment for Google Colab
# !pip install -q --upgrade ipympl
# from google.colab import output
# output.enable_custom_widget_manager()
```

but I'm going to leave it uncommented by default. That should make it work in binder and colab.
