### ISSUE TITLE
missing dep(s) on binder

### ISSUE THREAD

**Issue by stevejpurves** [PyLops/pylops_transform2022#4]
When running on binder based on this repo I had to:

1. comment out `import cupy` (expected for binder maybe, but I got a missing package error)
2. run `!pip install sympy` to avoid a missing package error.

**Comment by mrava87** [comment]
Thanks, 1 is for the Pylops_v2 repo right?

**Comment by mrava87** [comment]
I added sympy to the requirements so that there is no need for pip install

**Comment by cako** [comment]
I'll leave this as wontfix for cupy because cupy can only be installed in some environments, namely those with Nvidia GPU + CUDA installed.

**Comment by mrava87** [comment]
I would maybe add a markdown cell just before the cupy cell with a warning (run this cell only if you have access to a machine with Nvidia GPU + CUDA installed, or something like that..)

**Comment by cako** [comment]
Done!
